export const colombiaCities = [
  'Leticia, Amazonas, Colombia',
  'Medellín, Antioquia, Colombia',
  'Rionegro, Antioquia, Colombia',
  'Apartadó, Antioquia, Colombia',
  'Turbo, Antioquia, Colombia',
  'Caucasia, Antioquia, Colombia',
  'Arauca, Arauca, Colombia',
  'Barranquilla, Atlantico, Colombia',
  'Puerto Colombia, Atlantico, Colombia',
  'Sabanalarga, Atlantico, Colombia',
  'Baranoa, Atlantico, Colombia',
  'Girardot, Cundinamarca, Colombia',
  'Fusagasugá, Cundinamarca, Colombia',
  'Zipaquirá, Cundinamarca, Colombia',
  'Facatativá, Cundinamarca, Colombia',
  'Cartagena, Bolivar, Colombia',
  'Magangué, Bolivar, Colombia',
  'El Carmen de Bolivar, Bolivar, Colombia',
  'Bogota, Colombia',
  'Tunja, Boyacá, Colombia',
  'Duitama, Boyacá, Colombia',
  'Sogamoso, Boyacá, Colombia',
  'Manizales, Caldas, Colombia',
  'Florencia, Caquetá, Colombia',
  'Yopal, Casanare, Colombia',
  'Popayán, Cauca, Colombia',
  'Santander de Quilichao, Cauca, Colombia',
  'Valledupar, Cesar, Colombia',
  'Aguachica, Cesar, Colombia',
  'Quibdó, Chocó, Colombia',
  'Montería, Córdoba, Colombia',
  'Lorica, Córdoba, Colombia',
  'Montelibano, Córdoba, Colombia',
  'Inírida, Guainía, Colombia',
  'San José del Guaviare, Guaviare',
  'Neiva, Huila, Colombia',
  'Pitalito, Huila, Colombia',
  'Riohacha, La Guajira, Colombia',
  'Maicao, La Guajira, Colombia',
  'Santa Marta, Magdalena, Colombia',
  'Ciénaga, Magdalena, Colombia',
  'Villavicencio, Meta, Colombia',
  'Pasto, Nariño, Colombia',
  'Ipiales, Nariño, Colombia',
  'Tumaco, Nariño, Colombia',
  'Cúcuta, Norde de Santander, Colombia',
  'Ocaña, Norde de Santander, Colombia',
  'Pamplona, Norde de Santander, Colombia',
  'Mocoa, Putumayo, Colombia',
  'Puerto Asís, Putumayo, Colombia',
  'Armenia, Qindío, Colombia',
  'Pereira, Risaralda, Colombia',
  'San Andrés Isla, San Andrés y Providencia, Colombia',
  'Bucaramanga, Santander, Colombia',
  'Barrancabermeja, Santander, Colombia',
  'San Gil, Santander, Colombia',
  'Sincelejo, Sucre, Colombia',
  'Ibagué, Tolima, Colombia',
  'El Espinal, Tolima, Colombia',
  'Cali, Valle del Cauca, Colombia',
  'Tuluá, Valle del Cauca, Colombia',
  'Palmira, Valle del Cauca, Colombia',
  'Buenaventura, Valle del Cauca, Colombia',
  'Cartago, Valle del Cauca, Colombia',
  'Buga, Valle del Cauca, Colombia',
  'Mitú, Vaupés, Colombia',
  'Puerto Carreño, Vichada, Colombia',
];
