import Head from 'next/head';
import { FC } from 'react';
import Footer from './Footer';
import HeaderNav from './Header';

interface LayoutProps {
  children: React.ReactNode;
  title?: string;
}

const data = [
  {
    title: 'About',
    links: [
      { label: 'Artists', link: '/artists' },
      { label: 'Pricing', link: '/pricing' },
    ],
  },
  {
    title: 'Project',
    links: [
      { label: 'Contribute', link: '/' },
      { label: 'Media', link: '/media' },
    ],
  },
  {
    title: 'Community',
    links: [
      { label: 'Join Discord', link: '/' },
      { label: 'Follow on Twitter', link: '/' },
    ],
  },
];

const Layout: FC<LayoutProps> = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title || 'Sillevon'}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='author' content='Sillevon' />
        <link rel='icon' href='/sillevon.svg' />
      </Head>
      <HeaderNav />
      <main>{children}</main>
      <Footer data={data} />
    </>
  );
};

export default Layout;
